# Generated by Django 2.2 on 2021-06-05 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_profile', '0003_auto_20210605_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='login_and_profile.HouseMembership'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('PURCHASED', 'purchased'), ('INVITED', 'invited'), ('CREATED', 'created'), ('HELPED', 'helped purchase'), ('REGISTERED', 'registered an account')], default='CREATED', max_length=32),
        ),
    ]
