# Generated by Django 2.2 on 2021-06-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_profile', '0004_auto_20210605_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('PURCHASED', 'purchased'), ('INVITED', 'invited'), ('CREATED', 'created'), ('HELPED', 'helped purchase'), ('REGISTERED', 'registered an account'), ('ACCEPTED', 'accepted invite to')], default='CREATED', max_length=32),
        ),
    ]
