# Generated by Django 2.2 on 2021-06-06 12:53

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_profile', '0005_auto_20210606_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(
                decimal_places=2, default=Decimal(0), max_digits=10),
        ),
    ]
